//! AutoResearch Baseline PR 草案（PHASE-5-01）— 默认 Shadow，不 merge、不改 Required。

use anyhow::{Context, Result};
use serde::Serialize;
use sha2::{Digest, Sha256};
use std::fs;
use std::path::Path;

#[derive(Debug, Serialize)]
pub struct AutoResearchReport {
    pub ok: bool,
    pub mode: &'static str,
    pub shadow: bool,
    pub baseline_digest: String,
    pub recommendations: Vec<String>,
    pub written: Vec<String>,
    pub note: String,
}

/// 生成 Shadow 研究摘要：读 baseline/budgets，输出建议 PR 草案路径（不 apply）。
pub fn generate_shadow_report(root: &Path, write: bool) -> Result<AutoResearchReport> {
    let baseline = root.join(".github/ci/baseline.toml");
    let budgets = root.join(".github/ci/budgets.toml");
    let raw_b = fs::read_to_string(&baseline).unwrap_or_default();
    let raw_g = fs::read_to_string(&budgets).unwrap_or_default();
    let digest = format!("{:x}", Sha256::digest(raw_b.as_bytes()));
    let mut recommendations = vec![
        "Keep reuse.enabled=false until attestation path is production-proven".into(),
        "Prefer docs_only planner path to skip build_test compile on pure docs PRs".into(),
        "Observe ci-required-shadow before any Ruleset dual-track (HUMAN)".into(),
    ];
    if raw_g.contains("fast_p95") {
        recommendations
            .push("Track fast_p95_seconds vs budgets.toml in weekly metrics template".into());
    }
    if raw_b.contains("PLACEHOLDER") || raw_b.contains("0.0.0-draft") {
        recommendations
            .push("baseline still draft/PLACEHOLDER — do not promote Required coverage".into());
    }
    let mut written = Vec::new();
    if write {
        let dir = root.join("evidence/ci/autoresearch");
        fs::create_dir_all(&dir).context("create autoresearch dir")?;
        let body = format!(
            r#"# AutoResearch Shadow Report

- mode: shadow
- baseline_digest_sha256: `{digest}`
- apply: **forbidden** without HUMAN review
- merge_recommendation: **do not merge as Required change**

## Recommendations

{recs}

## Non-claims

- Not Goal Achieved
- Not Ruleset cutover
- Not production image pin

Generated by `cargo xtask ci autoresearch --write`.
"#,
            recs = recommendations
                .iter()
                .map(|r| format!("- {r}"))
                .collect::<Vec<_>>()
                .join("\n")
        );
        let out = dir.join("latest-shadow.md");
        fs::write(&out, body).context("write autoresearch report")?;
        written.push(out.display().to_string());
    }
    Ok(AutoResearchReport {
        ok: true,
        mode: "shadow",
        shadow: true,
        baseline_digest: digest,
        recommendations,
        written,
        note: "AutoResearch default Shadow; HUMAN must review before any baseline activation"
            .into(),
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ci::repo_root_from_manifest;

    #[test]
    fn shadow_report_ok() {
        let root = repo_root_from_manifest();
        let r = generate_shadow_report(&root, false).unwrap();
        assert!(r.ok);
        assert!(r.shadow);
        assert!(!r.recommendations.is_empty());
        assert_eq!(r.baseline_digest.len(), 64);
    }
}
